[package]
name = "v2ex-sign-in"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.48.0",features = ["full"]}
reqwest = { version = "0.12", features = ["cookies"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
dotenvy = "0.15"
config = "0.15"
regex = "1.10"