[package]
name = "v2ex-sign-in"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = "3"
serde = { version = "1.0", features = ["derive", "rc"] }
anyhow = "1"
config = { version = "0.15", default-features = false, features = ["toml", "yaml"] }
regex = "1.10"
lettre = "0.11"
url = "2"